### PR TITLE
fix transpose position and bias selection

### PR DESCRIPTION
**Pull request by NKWBTB**

### CODE REVIEW

**Comment by forrestbao** [comment]
@NKWBTB I think i just fixed minutes ago when I redid the slides for Fisher's. Can you check?

**Comment by forrestbao** [comment]
But you seem to be right that m1 and m2 should be averaged by size of the two classes respectively.

**Comment by forrestbao** [comment]
Hold on. No need to average m1 and m2 again when computing the bias, because they are already averaged. See my latest slides.

**Comment by NKWBTB** [comment]
Actually (|C1|m1+|C2|m2) / (|C1|+|C2|) is the center of all sample points while (m1+m2) / 2 is the center of the two class center point. If |C1| != |C2| then the two center point might be different.

**Comment by forrestbao** [comment]
It depends on where you want the decision hyperplane to lay. Should it be the center of all samples or the midway of the two centers? In my latest slides, i actually picked the later.

**Comment by NKWBTB** [comment]
Yes, you are right. 
The fix minutes ago should work.

Just add the pull request because of students asking me about the hw2.

**Comment by forrestbao** [comment]
Thanks so much for helping the students and updating the slides proactively.

**Pull request closed without merging**
